# Generated by Django 3.1.5 on 2021-10-22 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_number', models.IntegerField()),
                ('item_name', models.CharField(max_length=30)),
                ('item_quantity', models.IntegerField(max_length=20)),
            ],
        ),
    ]
